### PR TITLE
Davids feeder rev05

### PR DESCRIPTION
**Pull request by daveismith**
- #113 - Removes 50 ohm series resistor R2
- Cleans ERC errors caused by missing NC and power flags
- Adds two vias on the index wheel to make board shops happier (JLCPCB and OSHPark had issues rendering with an empty drill file)
- Adds github action to export production files on each commit / PR
- Adds parts for a JLCPCB output

### CODE REVIEW

**Comment by daveismith** [comment]
Sorry for all the noise. I was trying to fine tune the triggers for the action. At this point, they should run and upload results as attachments to the actions when running as a check on a PR or in someone's personal fork as a result of a commit. When a push / PR merge happens in @sphawes version of the repo, it will generate a new commit with the changed schematic, gerber, bom, cpl, step and image files.

**Review by G-Pereira — CHANGES_REQUESTED** [review]
LGTM! I think adding the export folder to a gitignore file would be useful to allow local testing without messing with the exports.
I don't know if we can set a filter like `**/pcb/**/export/` or if we need to add a separate gitignore file to each pcb folder.

**Comment by daveismith** [comment]
@G-Pereira - In the little bit of research I did, it seems like you can't ignore a file which is in the repository. It will always show up as changed. A `git update-index --assume-unchanged <file>` might achieve what you're looking for, but the user would need to do it locally. I haven't run across a way to set this in the remote so it propagates to all users. I wonder if it's something that once we're a bit more familiar with git lfs we might be able to achieve with locking by assigning the lock to the github actions use and never releasing it.

**Comment by G-Pereira** [comment]
@daveismith You can do that with [git rm](https://git-scm.com/docs/git-rm)

**Review by G-Pereira — APPROVED** [review]
Perfect!

**Pull request merged**
