### PR TITLE
Replaced Vacuum sensing with HX711

### PR DESCRIPTION
**Pull request by G-Pereira**
After a discussion about the complexity of implementing analog read in marlin at #55 and #65 it seems it isn't worthwhile to go down the ADC read path. For that reason I see no reason to keep that circuit on board so we might as well throw in the HX711 and test it on board!

### CODE REVIEW

**Comment by daveismith** [comment]
Looking at it, the few comments I have are:
- Pins connected to ICC don't look connected to me. Maybe consider putting a wire with the label adjacent.
- The ICC signal causes an ERC issue. A power flag is needed. I realize there are a number of them which need to be corrected elsewhere but it would be good to not introduce more.

**Comment by G-Pereira** [comment]
@daveismith Thank you for your review! I am always looking to improve my schematics clarity. I've made some change which I believe it improves the understanding of how the sensor is supplied (current source):
image

**Comment by martinbogo** [comment]
Here are my concerns:

- The HX711 is designed to read the differential output from a force load cell.   Does a vacuum sensor have the same voltage range and amplification requirements/specs?
- The datasheet for the HX711 states the following.  Is it appropriate for the vacuum sensor?
`Analog Inputs Channel A differential input is designed to interface directly with a bridge sensor’s differential output. It can be programmed with a gain of 128 or 64. The large gains are needed to accommodate the small output signal from the sensor. When 5V supply is used at the AVDD pin, these gains correspond to a full-scale differential input voltage of ±20mV or ±40mV respectively. Channel B differential input has a fixed gain of 32. The full-scale input voltage range is ±80mV, when 5V supply is used at the AVDD pin.`
- How do you imagine this to be implemented in Marlin?  How is the sensor to be read?  How often?

**Comment by G-Pereira** [comment]
According to the concerns shared here and the discussion on the discord an external ADC will be preferred. This branch will continue open if we want to return to this.

**Pull request closed without merging**
