### PR TITLE
A4 assembly

### PR DESCRIPTION
**Pull request by tobiasfalk**
I started to create an version of the Assembly where everything is done with Assembly4 as discussed #133.
for that I coped everything to an separate folder because I needed to add connection points to the 3D models.

the XZ Gantry is finished

At last I'm sorry for my bad English.

Greetings Tobias Falk

### CODE REVIEW

**Comment by tobiasfalk** [comment]
Screenshot_20210205_143635

**Comment by G-Pereira** [comment]
Hey @tobiasfalk this is awesome! However there are several on going fixes to the cad and you should base your work on the cad-pn branch since we will not be able to merge FreeCAD files.

**Comment by tobiasfalk** [comment]
ok

**Comment by tobiasfalk** [comment]
this should do it than

**Pull request closed without merging**
