### PR TITLE
Cad pn tp fdm 0014, added FDM number and changed datum plate atachment

### PR DESCRIPTION
**Pull request by tobiasfalk**

### CODE REVIEW

**Comment by tobiasfalk** [comment]
Screenshot_20210304_234831
Screenshot_20210304_234813

**Review by G-Pereira — CHANGES_REQUESTED** [review]
Hey @tobiasfalk !
All good except two things:
- PN should be **FDM-0014-00**
- PN emboss should be 0.4mm

**Comment by tobiasfalk** [comment]
this should be it than

**Review by G-Pereira — APPROVED** [review]
LGTM!

**Pull request merged**
