### PR TITLE
Add MOSFET driver and freewheeling diodes

### LINKED ISSUE #69: [Mobo] IRF540N MOSFETs can not be operated directly with 3.3V MCU output
The IRF540N isn't a logic level MOSFET. To fully switch on, it requires about 10V at it's gate.
If driven by a 3.3V MCU output, it doesn't switch on reliably and may heat up significantly.
For reliable operation, a gate driver circuit with appropriate supply voltage is required.

### PR DESCRIPTION
**Pull request by G-Pereira**
Fixes #69 and #70, Be sure to merge PR #74 first!
image

### CODE REVIEW

**Comment by G-Pereira** [comment]
Routing wasn't done since a lot of components have to be moved around and I would like to open for discussion if we should include status LEDs, or other features to this

**Comment by sphawes** [comment]
@G-Pereira Is the main reason behind adding the mosfet driver to facilitate driving the IRF540N? That was a mistake on my part, that part number is incorrect. I'd prefer to use a mosfet that doesnt require a driver if possible to keep the BOM cost low. These outputs aren't meant for PWM driving anything, so I don't think it's necessary to add a driver for that reason. It's meant for just pumps and solenoids, so our only real limitation here is making sure the gate threshold voltage is healthily below 3.3V and doesn't pull too much current.

I used a 'fet from LCSC that is out of stock, so I'm looking for a reliable replacement with the same footprint. I'm looking at the [TSM900](https://www.digikey.com/en/products/detail/taiwan-semiconductor-corporation/TSM900N10CP-ROG/7360606) right now. Would love to know your thoughts on it.

The diode makes a ton of sense, I'm surprised I haven't broken something without them yet!

**Comment by G-Pereira** [comment]
That makes sense, I will check that tomorrow!

**Comment by G-Pereira** [comment]
The TSM900 has low gate charge which is good to keep turn-on time reasonably high for low gate currents (logic level switch) however the gate threshold voltage is high for 3.3V gate voltage.
Calculations are done as follows:
Having **Qg** (gate charge) for 3.3V gate-source voltage **Vgs** and assuming 5mA for the maximum gate current **Ig**, the gate resistor **Rg** and rise time **tr** are calculated as follows:
```
tr = Qg/Ig
Rg = Vgs/Ig = 660 ohms
```
A few transistors were analysed and its price/un for 10 units is checked on [LCSC](https://lcsc.com):

[TSM900](https://lcsc.com/product-detail/MOSFET_Taiwan-Semiconductor-Taiwan-Semicon-TSM900N06CP-ROG_C478624.html) (US$0.1395):
- tr = 0.8 us
- Vth = 2.5V
- Id (max@3.3V Vgs) = 30A

[UMW15N10](https://lcsc.com/product-detail/MOSFET_UMW-Youtai-Semiconductor-Co-Ltd-UMW15N10_C359106.html) (US$0.1198):
- tr = 5.5 us
- Vth = 2.5V
- Id (max@3.3V Vgs) = _unknown_

[IRLR3410TRPBF](https://lcsc.com/product-detail/MOSFET_International-Rectifier_IRLR3410TRPBF_International-Rectifier-IR-IRLR3410TRPBF_C3017.html) (US$0.4177) **highly available on LCSC**:
- tr =  2 us
- Vth = 2 V
- Id (max@3.3V Vgs) = 7A

[NCE6050KA](https://lcsc.com/product-detail/MOSFET_Wuxi-NCE-Power-Semiconductor-NCE6050KA_C96013.html) (US$0.1601):
- tr = 5 us
- Vth = 2.5V
- Id (max@3.3V Vgs) = 30A

[SE4020B](https://lcsc.com/product-detail/MOSFET_SINO-IC-SE4020B_C396085.html) (US$0.1289 **(5 units)**):
- tr = 1.4 us
- Vth = 2V
- Id (max@3.3V Vgs) = 20A

I can conclude that TSM900 seems to be a good option due to its low price, low rise time (remains less time in conditions that produce more heat) however its threshold voltage could be better. I will pick SE4020B due to its reduced threshold voltage, lower Rds-on, good price and high availability on LCSC.

**Comment by G-Pereira** [comment]
The vacuum sensor amplifier needs 12V any ideas for 24V support @sphawes ?

**Comment by G-Pereira** [comment]
@sphawes The MOSFET you suggested is actually available at Digikey and the SE4020B is not. The datasheet does not tell the Rds-on for a 3.3V gate but it should be fine for the loads we are dealing with since they specify 100 mOhm.for a 4.5V gate.
Only routing is left, I will take care of that tomorrow.
A part from this PR I think I can order the MOBO in order to see things flowing and better understand its priorities.

**Comment by sphawes** [comment]
Beautiful. Merging on in!

**Pull request merged**
