### PR TITLE
Script to generate 3D prints

### PR DESCRIPTION
**Pull request by G-Pereira**
# Description
Python script to generate STL files for printing.

## Algorithm
- Opens the assembly file
- Filters parts by name (must include "FDM")
- Exports each one to STL

## GitHub Action
If a CAD file is changed:
- Installs FreeCAD
- Runs the script
- Pushes STL files to the repository

### CODE REVIEW

**Comment by G-Pereira** [comment]
Done!

**Comment by G-Pereira** [comment]
Now it only runs when a PnP CAD file is changed! The bot didn't make a commit because the file wasn't actually changed only "re-saved"

**Comment by arturo182** [comment]
Is there a benefit of .obj over .stl or was that just easier to script?

**Comment by G-Pereira** [comment]
It was easier, but I will check later today if I can save as STL. Actually, if I can save as 3MF would be really nice to result in nicer circles 🤔

**Comment by G-Pereira** [comment]
@arturo182  It works great with STLs!
@sphawes Maybe you know this more than I do: Should we use STL which quality sucks but has tremendous support or move to something nicer like OBJ or AMF? FreeCAD does not support 3MF just yet, but according to [this](https://all3dp.com/1/3d-printer-file-format/) AMF and OBJ are better and the most popular slicers support them.

**Comment by G-Pereira** [comment]
Sorry for the spam, I was not understanding the issue I was having

**Comment by G-Pereira** [comment]
Now it's ready for merge!

**Comment by sphawes** [comment]
@G-Pereira I think STL is the way to go here. It's ubiquitous, and although it might not be quite as precise as others, it's more than enough for our purposes.

This is an awesome addition and will help folks get printing much faster, and make sure they're printing the most up to date parts. Thank you for the contribution! I'll merge now.

**Pull request merged**
