### PR TITLE
Ring Light decoupling capacitors

### PR DESCRIPTION
**Pull request by g2pmas**
Few RingLight PCB improvements: 
- added required ws2812b bypass capacitors C1-C8;
- added JST vertical connector on bottom layer according to issue #87
- added 3d model of mentioned JST connectors and BOM pn.

### CODE REVIEW

**Comment by G-Pereira** [comment]
Hi @g2pmas thank you for your contribution! I see you made your changes using a nightly version of KiCAD. We are currently using KiCAD 5.1.x . So we can't merge this. Sorry!

**Comment by daveismith** [comment]
On the rear, you have `REV001<<<HASH>>>`, please change that to `REV001<<hash>>` so the automatic hash insertion will work.

**Comment by g2pmas** [comment]
@daveismith I fixed "hash" tag as required.

**Comment by daveismith** [comment]
Right now you have

```
IndexPnP by S.HAWES
RingLight
REV001<<<hash>>>
G.Mascolo
20210204
```

which produces:

ringLight-bottom

That encloses the hash in an extra, un-needed set of angle brackets. It needs to be as below.

```
IndexPnP by S.HAWES
RingLight
REV001<<hash>>
G.Mascolo
20210204
```

Notice the difference is the removal of one set of < > tags (there should only be two).

**Comment by g2pmas** [comment]
@daveismith I'm sorry. May you check it now?

**Comment by daveismith** [comment]
The replacement text looks good to me. I'll let @G-Pereira review and merge.

**Review by G-Pereira — CHANGES_REQUESTED** [review]
Hey @g2pmas ! Here's my review:
- Capacitors should have a value.
- JST connectors should have a different name (value) on the schematic so they are processed as different parts
- STEP files should not be included in the library because 3d model offset would have to be set for each component on the PCB. You can check [here](https://forum.kicad.info/t/tutorial-how-to-make-a-footprint-in-kicad-5-1-x-from-scratch/11092/5) how you can load a STEP file and a KiCAD footprint into FreeCAD set the correct placement of the 3d model and then export the wrl  file.
- The designators on the silkscreen are weird :D you have some vertical and some horizontal. Try keeping one orientation for most designators and only use the other if you really need to.

Other than that your changes are good!

**Comment by g2pmas** [comment]
@G-Pereira you should have a job in TESLA PCB layout design team. There are a lot of weird silk screen designators in their PCB :-D
immagine
I will do other required changes but try not to be too fussy :-)

**Comment by G-Pereira** [comment]
@g2pmas I am currently searching for a job, are you making me an offer? :)

**Comment by daveismith** [comment]
@g2pmas, do you expect to be able to address the changes requested above soon?

**Comment by G-Pereira** [comment]
I will close this since we are moving to angled lights both for the up and down light rings

**Pull request closed without merging**
