### PR TITLE
Resizes Buck Converter ( Fixes #235 )

### LINKED ISSUE #235: [MOBO] - Buck Converter Part Choice
**Motherboard Revision:** REV03

**Context:** 
- The REV02 Mobo used a TPS54336, rated for 3 amp output. This is quite overkill if we aren't powering the feeders through it anymore. 
- The current buck converter IC in REV03 Beta is TPS54531. This is rated for a bit more current output, and is a bit harder to source.

**Enhancement Description:** 
- Pick and implement a replacement buck converter that 1) Is easily sourced through Digikey/LCSC/Mouser, 2) reasonable price (up to a couple bucks), 3) has a low number of required components to implement, and 4) has a current output rating of at least 2 amps (accounts for 500ma USB spec for the three USB ports, then 500ma for the LEDs, and powering the 3.3v LDO).

### PR DESCRIPTION
**Pull request by G-Pereira**
image

### CODE REVIEW

**Review by daveismith — COMMENTED** [review]
So I'm not necessarily the best person to review a power supply design. I can say this mostly matches the schematic though there are the following differences that I wanted to highlight:

- diode (D3) between ground and the output is a different type (which might have an impact)
- output capacitor (C29) differs  different (ref design has 220uF vs index design having 100uF)
- note: 8.2.1.3.4 in the data sheet indicates how to select the cap and inductor

**Comment by cad435** [comment]
Luckily, I used that exact converter for a design already done and proven. This was my schematic:
image

As far as I can see, its really the same. the only difference is a second output 100nF MLCC (C31 in my schematic) I'd add that, to ensure maximum output stability. The used feedback network are nearly identical (3.26k vs. 3.24k) which will in theory will produce 4.964V (vs. 4.985V) with 1.5% accuracy (+ accuracy from the resistors). Should be good!

**Comment by G-Pereira** [comment]
Thank you @daveismith and @cad435. We also have 100uF at the input of the buck along with the capacitors for each motor so there's already a lot of input capacitance.
I am adding an extra output capacitor since the datasheet recommends a minimum of 133uF as the minimum output capacitance.

**Comment by daveismith** [comment]
Can you post an image of the updated schematic block?

**Comment by G-Pereira** [comment]
Sure!
image

**Comment by cad435** [comment]
I'd actually go with a 100nF MLCC for C30 instead of a 100uF electrolytic...
The MLCCs usually have a lot less ESR and stability will usually benefit more from it than a second 100uF

If you're unsure because we don't meet the 133uF output capacitance then, I suggest upgrading C25 to 220uF, or add ANOTHER MLCC with 22/47uF usually the combined package footprint of two MLCCs even when one of them is 1206 is less than one of the bulky Elektrolytic. (I suppose they are in those Tin-Can SMD packages now)

**Comment by G-Pereira** [comment]
@cad435 thanks for your review!
Regarding reducing the capacitance the manufacturer's recommendation is set to ensure stability, this way we also can be confident that our power supply works as expected on **every** board. For that reason I've looked to several options:
- I've looked for 220uF capacitors in order to replace all 100uF used on the board for 220uF but since they are significantly bigger they wouldn't fit under the stepper drivers where they are also used.
- Adding a second MLCC with at least 33uF requires an additional BOM part
- Adding another electrolytic capacitor takes up more board area
In the end, the last option was the one I found most suited for our goal.

As a side note our MOSFETs allow a maximum of 30V Vds

**Comment by vysocan** [comment]
Hello @G-Pereira, I happen to use the same IC. There is formula for output capacitor in 8.2.1.2.4.2 in datasheet. For 15uH and 5V it happen to be exactly 220uF as in example schematics. I use actually a bit more expensive lowESR tantalum 3x100uF (for different voltage) size D caps. They are rock stable over years, small and low profile also.

**Comment by daveismith** [comment]
If you look at the doc, they use an 18kHz crossover to get the 220uF inductor. I agree with your with math if we select a 30kHz crossover frequency.

image

If we were to put two 100uF caps in parallel as you suggested earlier, I calculate the crossover as:

image

**Comment by vysocan** [comment]
Exactly as David says. I've used 18kHz. I guess better then the edge of recommended 30kHz. My recommendation was to stay with 2x100uF. And maybe use tantalum if suited.

**Comment by G-Pereira** [comment]
@daveismith i wasn't suggesting designing for 30kHz, I was just checking what the limits would be

**Comment by G-Pereira** [comment]
Ok, thanks for your reviews. I've got everything in. Merging

**Pull request merged**
