### PR TITLE
Cad pn tp fdm 0013 02 x idler mount remodeling

### PR DESCRIPTION
**Pull request by tobiasfalk**
Remodeld FDM-0013-02_x-idler-mount.FCStd because it had a Topology Problem

### CODE REVIEW

**Comment by daveismith** [comment]
@G-Pereira - should this have triggered a GH action to generate new STL files? Also, who can review and approve mechanical cad?

**Review by G-Pereira — CHANGES_REQUESTED** [review]
@daveismith I am not sure why this isn't triggering a GitHub action, let's see if it does when we merge.
Since these fixes won't have any design changes I can help review them.
Regarding this @tobiasfalk I noticed you made an indentation for the idler, that was a good addition! In this case, it's fine but try to keep modifications to a minimum so we can quickly review this.
Regarding the fixes, they don't seem to work. I've tried opening the first sketch and it complained about broken constraints. Any ideas @meutzitzu ?
image

**Comment by meutzitzu** [comment]
Idk, on my end I can open and edit every sketch

**Comment by G-Pereira** [comment]
@tobiasfalk I just checked again and I can open all the sketches as well. Thanks @meutzitzu !
Right now I see some things that need to be fixed:
- Part number embossed should be **FDM-0013-02**
- Scketch008 needs one more constraint (it has one degree of freedom)
- Change font to **../../../../lib/fonts/DejaVuSans-Bold.ttf**

**Comment by tobiasfalk** [comment]
@G-Pereira the requested changes should be made

**Comment by G-Pereira** [comment]
Perfect, thank you!

**Review by G-Pereira — COMMENTED** [review]
Good job!

**Pull request merged**
